customCommands:
  - key: 't'
    command: "helix-open {{.SelectedFile.Name | quote}}"
    context: 'files'
    description: 'open in helix'
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
