abbreviation_file: ~/.config/abbrgen/abbreviations.csv
keyboard:
  layout: engram
  same_column_combo_penalty: 2
  same_row_combo_penalty: 2
  scissor_penalty: 3
  stagger: column
  type: standard
min_word_length: 3
overwrite_abbreviations: true
overwrite_alts: false
